####
#### The annotation evidence aggregate description file for GOlr and
#### AmiGO.
####
id: bbop_ann_ev_agg
description: A description of annotation evidence aggregate for GOlr and AmiGO.
display_name: Evidence Aggregate
document_category: annotation_evidence_aggregate
weight: 10
default_fields_and_boosts: foo^1.0
fields:
  # - id: document_category
  #   description: The category of the document in the Solr index.
  #   display_name: Category
  #   type: string
  #   property_type: fixed
  #   property: annotation_evidence_aggregate
  - id: id
    description: Bioentity id.
    display_name: Acc
    type: string
    property: ???
  - id: bioentity_id
    description: "Column 1 + columns 2."
    display_name: Bioentity id
    type: string
    property: ???
  - id: bioentity_label
    description: Column 3.
    display_name: Bioentity label
    type: string
    property: ???
    searchable: true
  - id: annotation_class
    description: Column 5.
    display_name: Annotation class
    type: string
    property: ???
  - id: annotation_class_label
    description: "Column 5 + ontology."
    display_name: Annotation class label
    type: string
    property: ???
    searchable: true
  - id: evidence_closure
    description: ???
    display_name: Evidence closure
    type: string
    cardinality: multi
    property: ???
  - id: evidence_with
    description: ???
    display_name: Evidence with
    type: string
    cardinality: multi
    property: ???
